/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IECL } from "./IECL";
export type { IEurocupLegends } from "./IEurocupLegends";
export type { IShirts } from "./IShirts";
export type { ITickets } from "./ITickets";
