/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IEurocupLegends__factory } from "./IEurocupLegends__factory";
export { IShirts__factory } from "./IShirts__factory";
export { ITickets__factory } from "./ITickets__factory";
