/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as tokens from "./tokens";
export type { tokens };
export type { EurocupLegends } from "./EurocupLegends";
